import pytest

from onepdd.repo import GitRepo, GopddPuzzle


@pytest.fixture()
async def pdd_repo():
    async with GitRepo(
        uri="https://github.com/monomonedula/cactoos.git",
        name="monomonedula/cactoos",
    ) as repo:
        yield repo


async def test_git_repo(pdd_repo: GitRepo):
    assert pdd_repo.id == "aHR0cHM6Ly9naXRodWIuY29tL21vbm9tb25lZHVsYS9jYWN0b29zLmdpdA"
    assert pdd_repo.head_commit_hash == ""
    assert await pdd_repo.parsed() == [
        GopddPuzzle(
            id="1453-4fdb169",
            ticket="1453",
            estimate=30,
            role="DEV",
            lines="126-129",
            body="Continue migration of tests to JUnit 5. Junit 4 Ruleshould be replaced with a Jupiter counterpart. `@Text(expected=..)` with `Throws`. After that remove this dependencies.",
            file="pom.xml",
            author="rultor",
            email="me@rultor.com",
            time="2023-09-14T21:50:14+03:00",
        ),
        GopddPuzzle(
            id="1434-2d5e9f2",
            ticket="1434",
            estimate=30,
            role="DEV",
            lines="265-272",
            body="In the continuation of #588, all the callsto Matchers should be replaced with their OO counterparts. This todo should be updated with a new one until everything is done. The newly covered classes should be added to the include configuration property below. At the end, the configuration property below should be completely removed so that calls to forbidden APIs always fail the build for every classes.",
            file="pom.xml",
            author="rultor",
            email="me@rultor.com",
            time="2023-09-14T21:50:14+03:00",
        ),
        GopddPuzzle(
            id="1615-71516fc",
            ticket="1615",
            estimate=30,
            role="DEV",
            lines="37-41",
            body="Extract fallback logic for Bytesto a separate class in accordance to other XXXWithFallback classes. Leave only basic exception handling in this class.",
            file="src/main/java/org/cactoos/bytes/UncheckedBytes.java",
            author="rultor",
            email="me@rultor.com",
            time="2023-09-14T21:50:14+03:00",
        ),
        GopddPuzzle(
            id="898-ecb19af",
            ticket="898",
            estimate=30,
            role="DEV",
            lines="36-39",
            body="Replace all the Collections.unmodifiableCollectionwith the {@link Immutable} from the cactoos codebase. That should be done because Elegant Object principles are against static methods.",
            file="src/main/java/org/cactoos/collection/Immutable.java",
            author="rultor",
            email="me@rultor.com",
            time="2023-09-14T21:50:14+03:00",
        ),
        GopddPuzzle(
            id="1572-00dd3d3",
            ticket="1572",
            estimate=30,
            role="DEV",
            lines="29-32",
            body="Exploit generic variance for package org.cactoos.functo ensure typing works as best as possible as it is explained in #1533 issue.",
            file="src/main/java/org/cactoos/func/package-info.java",
            author="rultor",
            email="me@rultor.com",
            time="2023-09-14T21:50:14+03:00",
        ),
        GopddPuzzle(
            id="1449-97d50e6",
            ticket="1449",
            estimate=30,
            role="DEV",
            lines="29-34",
            body="We must find all the classes that closes stream of{@link org.cactoos.Input} or {@link org.cactoos.Output} that have been passed to them and document them about this behaviour and refer them to the existence of {@link org.cactoos.io.CloseShieldInput} and {@link org.cactoos.io.CloseShieldOutput} and how to use them.",
            file="src/main/java/org/cactoos/io/package-info.java",
            author="rultor",
            email="me@rultor.com",
            time="2023-09-14T21:50:14+03:00",
        ),
        GopddPuzzle(
            id="1533-0f45a3d",
            ticket="1533",
            estimate=30,
            role="DEV",
            lines="34-37",
            body="Exploit generic variance for package org.cactoos.ioto ensure typing works as best as possible as it is explained in #1533 issue.",
            file="src/main/java/org/cactoos/io/package-info.java",
            author="rultor",
            email="me@rultor.com",
            time="2023-09-14T21:50:14+03:00",
        ),
        GopddPuzzle(
            id="1254-a05152e",
            ticket="1254",
            estimate=30,
            role="DEV",
            lines="37-40",
            body="Make {@link Joined} implements directly {@link List}and delegate each operation to {@link JoinedListIterator} as if lists joined were one list.",
            file="src/main/java/org/cactoos/list/Joined.java",
            author="rultor",
            email="me@rultor.com",
            time="2023-09-14T21:50:14+03:00",
        ),
        GopddPuzzle(
            id="1254-dea7804",
            ticket="1254",
            estimate=30,
            role="DEV",
            lines="39-43",
            body="We should implement mutable operations (#add, #set and #remove)according to their javadoc. Also, the behaviour of adding/setting/removing an element when the cursor is in between two listerators should be well documented in this class (because there are multiple options in that case).",
            file="src/main/java/org/cactoos/list/JoinedListIterator.java",
            author="rultor",
            email="me@rultor.com",
            time="2023-09-14T21:50:14+03:00",
        ),
        GopddPuzzle(
            id="1533-62ec85c",
            ticket="1533",
            estimate=30,
            role="DEV",
            lines="29-32",
            body="Exploit generic variance for package org.cactoos.mapto ensure typing works as best as possible as it is explained in #1533 issue.",
            file="src/main/java/org/cactoos/map/package-info.java",
            author="rultor",
            email="me@rultor.com",
            time="2023-09-14T21:50:14+03:00",
        ),
        GopddPuzzle(
            id="1567-495bd50",
            ticket="1567",
            estimate=30,
            role="DEV",
            lines="29-32",
            body="Exploit generic variance for package org.cactoos.procto ensure typing works as best as possible as it is explained in #1533 issue.",
            file="src/main/java/org/cactoos/proc/package-info.java",
            author="rultor",
            email="me@rultor.com",
            time="2023-09-14T21:50:14+03:00",
        ),
        GopddPuzzle(
            id="1569-e3c182a",
            ticket="1569",
            estimate=30,
            role="DEV",
            lines="29-32",
            body="Create tests for the semantics of relaxed wildcardsin changed classes of {@link org.cactoos.scalar} package in #1569, which is a child of #1533.",
            file="src/main/java/org/cactoos/scalar/package-info.java",
            author="rultor",
            email="me@rultor.com",
            time="2023-09-14T21:50:14+03:00",
        ),
        GopddPuzzle(
            id="1533-fe6be0d",
            ticket="1533",
            estimate=30,
            role="DEV",
            lines="29-32",
            body="Exploit generic variance for package org.cactoos.setto ensure typing works as best as possible as it is explained in #1533 issue.",
            file="src/main/java/org/cactoos/set/package-info.java",
            author="rultor",
            email="me@rultor.com",
            time="2023-09-14T21:50:14+03:00",
        ),
        GopddPuzzle(
            id="1533-650d912",
            ticket="1533",
            estimate=30,
            role="DEV",
            lines="29-32",
            body="Exploit generic variance for package org.cactoos.timeto ensure typing works as best as possible as it is explained in #1533 issue.",
            file="src/main/java/org/cactoos/time/package-info.java",
            author="rultor",
            email="me@rultor.com",
            time="2023-09-14T21:50:14+03:00",
        ),
        GopddPuzzle(
            id="1335-cfcafe2",
            ticket="1335",
            estimate=30,
            role="DEV",
            lines="37-42",
            body='Following the rewrite of the Number implementationsin cactoos, the three methods below prefixed by overflow where adapted because they started to give different results. The task is to investigate thoroughly what is a "correct" behaviour concerning overflow in the case of SumOf and adapt the tests and the code to make this obvious and clear.',
            file="src/test/java/org/cactoos/number/SumOfTest.java",
            author="rultor",
            email="me@rultor.com",
            time="2023-09-14T21:50:14+03:00",
        ),
        GopddPuzzle(
            id="1425-e7207c9",
            ticket="1425",
            estimate=30,
            role="DEV",
            lines="28-32",
            body="Continue replacing usage of MatcherAssert.assertThat withAssertion from cactoos-matchers. Keep PR short and limit the changes to single package. Update this puzzle for the next package. After all packages are done, add MatcherAssert to forbidden-apis.txt",
            file="src/test/java/org/cactoos/package-info.java",
            author="rultor",
            email="me@rultor.com",
            time="2023-09-14T21:50:14+03:00",
        ),
    ]


async def test_repo_gets_deleted():
    async with GitRepo(
        uri="https://github.com/monomonedula/cactoos.git",
        name="monomonedula/cactoos",
    ) as repo:
        assert repo.path.exists()
        path = repo.path
    assert not path.exists()
